# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watstat', '0004_auto_20161114_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='adm_level',
            name='checkin',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
