# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 06:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatWO',
            fields=[
                ('id_catwo', models.AutoField(primary_key=True, serialize=False)),
                ('catwo_name', models.CharField(max_length=50, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0432\u043e\u0434\u043d\u043e\u0433\u043e \u043e\u0431\u044a\u0435\u043a\u0442\u0430')),
                ('catwo_description', models.CharField(blank=True, max_length=200, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0432\u043e\u0434\u043d\u043e\u0433\u043e \u043e\u0431\u044a\u0435\u043a\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0432\u043e\u0434\u043d\u043e\u0433\u043e \u043e\u0431\u044a\u0435\u043a\u0442\u0430',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0432\u043e\u0434\u043d\u044b\u0445 \u043e\u0431\u044a\u0435\u043a\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='ExBodyData',
            fields=[
                ('id_exbody', models.AutoField(primary_key=True, serialize=False)),
                ('name_exbody', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043c\u0435\u0441\u0442\u043d\u043e\u0433\u043e \u0438\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u0438 \u0440\u0430\u0441\u043f\u043e\u0440\u044f\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u043e\u0440\u0433\u0430\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u041e\u0440\u0433\u0430\u043d \u0432\u043b\u0430\u0441\u0442\u0438',
                'verbose_name_plural': '\u041e\u0440\u0433\u0430\u043d\u044b \u0432\u043b\u0430\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='InvWatObjLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_name', models.CharField(max_length=100)),
                ('inv_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvWatObjPoly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_name', models.CharField(max_length=100)),
                ('inv_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineWO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PolygonWO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='SoatoData',
            fields=[
                ('id_soato', models.AutoField(primary_key=True, serialize=False)),
                ('soato_kode', models.CharField(max_length=10, verbose_name='\u041a\u043e\u0434 \u0421\u041eATO')),
                ('soato_name', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('soato_nameadd', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435')),
            ],
            options={
                'db_table': 'SoatoData',
                'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043f\u043e \u043a\u043e\u0434\u0443 \u0421\u041eA\u0422\u041e',
                'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043f\u043e \u043a\u043e\u0434\u0430\u043c \u0421\u041e\u0410\u0422\u041e',
            },
        ),
        migrations.CreateModel(
            name='TargetArendaWO',
            fields=[
                ('id_targetarendawo', models.AutoField(primary_key=True, serialize=False)),
                ('targetarendawo_name', models.CharField(blank=True, max_length=200, verbose_name='\u0426\u0435\u043b\u044c \u043f\u0435\u0440\u0435\u0434\u0430\u0447\u0438 \u0432 \u0430\u0440\u0435\u043d\u0434\u0443')),
            ],
            options={
                'verbose_name': '\u0426\u0435\u043b\u044c \u043f\u0435\u0440\u0435\u0434\u0430\u0447\u0438 \u0432 \u0430\u0440\u0435\u043d\u0434\u0443',
                'verbose_name_plural': '\u0426\u0435\u043b\u0438 \u043f\u0435\u0440\u0435\u0434\u0430\u0447\u0438 \u0432 \u0430\u0440\u0435\u043d\u0434\u0443 ',
            },
        ),
        migrations.CreateModel(
            name='TargetObosobWOuse',
            fields=[
                ('id_targetobosobwouse', models.AutoField(primary_key=True, serialize=False)),
                ('targetobosobwouse_name', models.CharField(blank=True, max_length=200, verbose_name='\u0426\u0435\u043b\u044c \u043e\u0431\u043e\u0441\u043e\u0431\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0434\u043e\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0426\u0435\u043b\u044c \u043e\u0431\u043e\u0441\u043e\u0431\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0434\u043e\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u0426\u0435\u043b\u0438 \u043e\u0431\u043e\u0441\u043e\u0431\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0434\u043e\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='TargetUseWO',
            fields=[
                ('id_targetusewo', models.AutoField(primary_key=True, serialize=False)),
                ('targetusewo_name', models.CharField(max_length=80, verbose_name='\u0426\u0435\u043b\u044c \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u044f \u0432\u043e\u0434\u043d\u044b\u043c\u0438 \u0440\u0435\u0441\u0443\u0440\u0441\u0430\u043c\u0438')),
            ],
            options={
                'verbose_name': '\u0426\u0435\u043b\u044c \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u044f \u0432\u043e\u0434\u043d\u044b\u043c\u0438 \u043e\u0431\u044a\u0435\u043a\u0442\u0430\u043c\u0438',
                'verbose_name_plural': '\u0426\u0435\u043b\u0438 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u044f \u0432\u043e\u0434\u043d\u044b\u043c\u0438 \u043e\u0431\u044a\u0435\u043a\u0442\u0430\u043c\u0438',
            },
        ),
        migrations.CreateModel(
            name='TargetUseWOExBody',
            fields=[
                ('id_targetusewoexbody', models.AutoField(primary_key=True, serialize=False)),
                ('targetusewoexbody_name', models.CharField(blank=True, max_length=80, verbose_name='\u0426\u0435\u043b\u0435\u0432\u043e\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0426\u0435\u043b\u0435\u0432\u043e\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0426\u0435\u043b\u0435\u0432\u043e\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='TypeWO',
            fields=[
                ('id_typewo', models.AutoField(primary_key=True, serialize=False)),
                ('typewo_name', models.CharField(max_length=50, verbose_name='\u0422\u0438\u043f \u0432\u043e\u0434\u043d\u043e\u0433\u043e \u043e\u0431\u044a\u0435\u043a\u0442\u0430 (\u043b\u0438\u043d\u0435\u0439\u043d\u044b\u0439/\u043f\u043b\u043e\u0449\u0430\u0434\u043d\u043e\u0439/\u0442\u043e\u0447\u0435\u0447\u043d\u044b\u0439)')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0432\u043e\u0434\u043d\u043e\u0433\u043e \u043e\u0431\u044a\u0435\u043a\u0442\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0432\u043e\u0434\u043d\u044b\u0445 \u043e\u0431\u044a\u0435\u043a\u0442\u043e\u0432',
            },
        ),
        migrations.AddField(
            model_name='invwatobjpoly',
            name='mygeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watres.PolygonWO'),
        ),
        migrations.AddField(
            model_name='invwatobjpoly',
            name='soato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watres.SoatoData'),
        ),
        migrations.AddField(
            model_name='invwatobjline',
            name='mygeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watres.LineWO'),
        ),
        migrations.AddField(
            model_name='exbodydata',
            name='soato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watres.SoatoData'),
        ),
        migrations.AddField(
            model_name='catwo',
            name='catwo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watres.TypeWO'),
        ),
    ]
