# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invwatobjline',
            name='id_catwo',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
