# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0002_invwatobjline_id_catwo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catwo',
            old_name='catwo_type',
            new_name='catwo_type_id',
        ),
    ]
