# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 08:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0003_auto_20160812_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='invwatobjline',
            name='test_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
