# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0004_invwatobjline_test_array'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invwatobjline',
            old_name='test_array',
            new_name='type_array',
        ),
        migrations.AddField(
            model_name='invwatobjline',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invwatobjline',
            name='descr',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invwatobjline',
            name='raion',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invwatobjline',
            name='inv_name',
            field=models.CharField(max_length=300),
        ),
    ]
