# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 12:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0005_auto_20160812_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='invwatobjpoly',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invwatobjpoly',
            name='descr_location',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invwatobjpoly',
            name='id_catwo',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invwatobjpoly',
            name='type_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
