# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 12:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0006_auto_20160815_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvWatObjPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_name', models.CharField(max_length=100)),
                ('inv_num', models.IntegerField()),
                ('id_catwo', models.IntegerField(blank=True)),
                ('type_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('amount', models.IntegerField()),
                ('descr_location', models.CharField(max_length=400)),
                ('mygeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watres.PolygonWO')),
                ('soato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watres.SoatoData')),
            ],
        ),
        migrations.CreateModel(
            name='PointWO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('point', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
