# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 13:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0007_invwatobjpoint_pointwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointwo',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
