# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0012_targetusewo_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTableLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_name', models.CharField(max_length=100)),
                ('inv_num', models.IntegerField()),
                ('catwo', models.CharField(max_length=150)),
                ('arraytype', models.CharField(max_length=250)),
                ('amount', models.IntegerField()),
                ('descr_location', models.CharField(max_length=400)),
            ],
        ),
    ]
