# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0013_reporttableland'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gvk',
            fields=[
                ('id_gvk', models.AutoField(primary_key=True, serialize=False)),
                ('gup', models.IntegerField(verbose_name='\u041a\u043e\u0434 \u0413\u0412\u041a')),
                ('oku', models.CharField(blank=True, max_length=9, verbose_name='\u0423\u041d\u041f')),
                ('ato', models.CharField(blank=True, max_length=10, verbose_name='ATO')),
                ('npr', models.CharField(blank=True, max_length=500, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u0434\u043f\u0440\u0438\u044f\u0442\u0438\u044f')),
                ('okpo', models.CharField(blank=True, max_length=12, verbose_name='\u041e\u041a\u041f\u041e')),
            ],
        ),
        migrations.CreateModel(
            name='Zat',
            fields=[
                ('id_zat', models.AutoField(primary_key=True, serialize=False)),
                ('kod', models.IntegerField(verbose_name='\u041a\u043e\u0434 \u041e\u041a\u041f\u041e')),
                ('okulp', models.CharField(max_length=9, verbose_name='\u0423\u041d\u041f')),
                ('ato', models.CharField(max_length=10, verbose_name='ATO')),
                ('npr', models.CharField(max_length=500, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u0434\u043f\u0440\u0438\u044f\u0442\u0438\u044f')),
            ],
        ),
    ]
