# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0014_gvk_zat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zat',
            name='ato',
            field=models.CharField(max_length=10, verbose_name='O\u041a\u0415'),
        ),
        migrations.AlterField(
            model_name='zat',
            name='kod',
            field=models.CharField(max_length=12, verbose_name='\u041a\u043e\u0434 \u041e\u041a\u041f\u041e'),
        ),
    ]
