# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0015_auto_20161014_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvk',
            name='correctlink',
            field=models.BooleanField(default=1, verbose_name='Correct'),
            preserve_default=False,
        ),
    ]
