# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0016_gvk_correctlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvk',
            name='newokpo',
            field=models.CharField(blank=True, max_length=12, verbose_name='\u041e\u041a\u041f\u041e \u0432\u0435\u0440\u0438\u0444\u0438\u0446\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439'),
        ),
    ]
