# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0017_gvk_newokpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvk',
            name='npr_zat',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u0434\u043f\u0440\u0438\u044f\u0442\u0438\u044f'),
        ),
    ]
