# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0021_auto_20161020_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttableland',
            name='idcatwo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
