# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0022_reporttableland_idcatwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetobosobwouse',
            name='checkin',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
