# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 09:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0023_targetobosobwouse_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table2Obosob',
            fields=[
                ('id_tableobosob', models.AutoField(primary_key=True, serialize=False)),
                ('inv_num', models.IntegerField()),
                ('name_d', models.CharField(blank=True, max_length=200, null=True)),
                ('data_d', models.CharField(blank=True, max_length=200, null=True)),
                ('wateruser', models.CharField(blank=True, max_length=300, null=True)),
                ('id_targetwuse', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('w_len', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('targetobosobwu', models.CharField(blank=True, max_length=500, null=True)),
                ('data_expl', models.CharField(blank=True, max_length=500, null=True)),
                ('document', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table3Arenda',
            fields=[
                ('id_tablearenda', models.AutoField(primary_key=True, serialize=False)),
                ('inv_num', models.IntegerField()),
                ('reasons', models.CharField(blank=True, max_length=200, null=True)),
                ('target_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('wateruser', models.CharField(blank=True, max_length=300, null=True)),
                ('id_arenda', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('part_len', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part_area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Table4Recreation',
            fields=[
                ('id_tablerecreation', models.AutoField(primary_key=True, serialize=False)),
                ('inv_num', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('responsible_b', models.CharField(blank=True, max_length=200, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('decision_num', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
