# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0024_table2obosob_table3arenda_table4recreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table4recreation',
            name='decision_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
