# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0027_auto_20161102_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='table3arenda',
            name='end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
