# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0028_table3arenda_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table3arenda',
            name='part_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='table3arenda',
            name='part_len',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
