# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0031_targetarendawo_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='linewo',
            name='id_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporttableland',
            name='inv_name',
            field=models.CharField(max_length=200),
        ),
    ]
