# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watres', '0032_auto_20161123_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointwo',
            name='id_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polygonwo',
            name='id_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
